version: "3"

services:
  db:
    container_name: laravel-db
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql #utilizei db para evitar conflitos com o 'database' do laravel (insira outro nome)
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - backend
  phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
    networks:
      - backend
  web:
    build: .
    container_name: laravel-web
    volumes:
      - ./:/var/www/html
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - backend
networks:
  backend:
    driver: bridge

