version: "3"

services: 
  db:
    container_name: laravel-db
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=laravel
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=password
  phpmyadmin:
    container_name: sisnumis-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'
  web:
    build: .
    container_name: laravel-web
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
